name: Update table

on:
  workflow_dispatch:
  schedule:
    - cron: "1 5 * 12 *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run script  
        run: python .github/tablegen.py

      - name: Git commit and push
        run: |
          git config user.email 'actions@github.com'
          git config user.name 'github-actions'
          git add .github/README.md
          git commit -m 'Update table'
          git push origin HEAD:${{ github.ref }}